### ISSUE TITLE
Erro ao Consultar Status Operacional

### ISSUE THREAD

**Issue by Marcelo-Kyan** [base4sistemas/sathub#1]
Na interface web do sathub quando eu peço para executar o status operacional retorna o seguinte erro:

```
ERROR in executor
 [/pacotes/SAT/base4sistemas/sathub-master/sathub/executor.py:94]:
 Erro executando "ConsultarStatusOperacional"
 --------------------------------------------------------------------------------
 Traceback (most recent call last):
  File "/pacotes/SAT/base4sistemas/sathub-master/sathub/executor.py", line 82, in _executar
    resposta = getattr(cliente, metodo)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/satcfe/clientelocal.py", line 117, in consultar_status_operacional
    return RespostaConsultarStatusOperacional.analisar(retorno)
  File "/usr/lib/python2.7/site-packages/satcfe/resposta/consultarstatusoperacional.py", line 91, in analisar
    ('ESTADO_OPERACAO', int),
  File "/usr/lib/python2.7/site-packages/satcfe/resposta/padrao.py", line 210, in analisar_retorno
    resultado[campo] = conversor(partes[indice])
  File "/usr/lib/python2.7/site-packages/satcfe/util.py", line 65, in as_datetime
    return datetime.strptime(value, '%Y%m%d%H%M%S')
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
 ValueError: time data '' does not match format '%Y%m%d%H%M%S'
```

**Comment by danielgoncalves** [comment]
Você está com uma versão mais antiga do projeto [SATCFe](https://github.com/base4sistemas/satcfe), embora não seja esse o problema. Aparentemente o equipamento SAT está retornando um valor `datetime` (data/hora ANSI) fora do padrão esperado. Se você puder informar a resposta bruta do equipamento, ajudaria bastante. Pra fazer isso, use esse snippet de código, em um terminal:

``` python
>>> from satcomum import constantes
>>> from satcfe import conf
>>> from satcfe.base import DLLSAT, FuncoesSAT

>>> conf.codigo_ativacao = '12345678'

>>> func = FuncoesSAT(DLLSAT(
...     caminho='/caminho/para/libsat.so',
...     convencao=constantes.STANDARD_C))
...

>>> func.consultar_status_operacional()
'560372|10000|Resposta com sucesso|||900004019|DHCP|010.000.000.111|30:40:03:19:19:40|255.255.255.000|010.000.000.001|010.000.000.001|010.000.000.001|CONECTADO|ALTO|4 GB|260 MB|20150922161957|01.00.00|00.06|35150908723218000186599000040190000856193055|00000000000000000000000000000000000000000000|00000000000000000000000000000000000000000000|20150916202924|20150922161841|20150708|20200708|0'
```

Daí me passa o resultado pra eu dar uma olhada. Me passa também qual equipamento SAT que você está usando, e verifique a versão da sua biblioteca.

**Comment by Marcelo-Kyan** [comment]
Retorno:
'195195|10000|Resposta com Sucesso|||900003522|static\n|192.168.000.100|00:07:25:15:14:cd|255.255.255.000|192.168.000.001|192.168.000.001|000.000.000.000|CONECTADO|ALTO|1870127104|1174929408|20150922165839|01.00.00|0.06|||||20150919233139|20150905|20200905|0'

**Comment by Marcelo-Kyan** [comment]
Tentei atualizar o satcfe mas continua o mesmo erro.
Parece que ele não está atualizando para última versão.

**Comment by danielgoncalves** [comment]
Na resposta que você postou, o campo 19 `DH_CFE` está vazio. Esse equipamento SAT nunca transmitiu nenhum CF-e para a SEFAZ. É mesmo desejável que a resposta considere essa possibilidade. Será preciso aguardar por uma correção para o problema.

Sobre atualização de dependências, não há qualquer relação com os projetos SATCFe ou SATHub. A [documentação do pip](https://pip.pypa.io/en/stable/) pode ajudar. Se a atualização não está funcionando, tente remover e re-instalar:

``` shell
$ pip uninstall -y satcomum satcfe
$ pip install satcfe
```

**Comment by Marcelo-Kyan** [comment]
Daniel, esquecí de falar. Equipamento SAT BEMATECH RB-1000 FI.
Versão da lib libbemasat.so.1.0.0
Outro detalhe:
Percebí que está sendo gravado um arquivo de log no diretório corrente chamado"C:\bemaSATlog_dd_mm_aaaa.xml".
Onde está a configuração desse caminho para que eu possa alterá-lo?

**Comment by Marcelo-Kyan** [comment]
Quanto ao caminho do log eu já descobrí.
É um arquivo de configuração da bematech    /etc/bemasat.xml   que tem uma tag <Path>C:</Path>

**Comment by Marcelo-Kyan** [comment]
Daniel, uma dúvida:
O XML da venda eu tenho que criar ou tem algum módulo do satcfe que faz isso?

**Comment by danielgoncalves** [comment]
Para criar o XML da venda, leia atentamente [este tópico](http://satcfe.readthedocs.org/pt_BR/latest/venda_cancelamento.html) da documentação. 

Para outras dúvidas, Marcelo, use o [Gitter](https://gitter.im/base4sistemas/satcfe) que é uma sala de bate-papos específica para este projeto e para os projetos relacionados. **Issues** não são para tirar dúvidas, mas para relatar anomalias no funcionamento esperado ou para sugerir funcionalidades.
